require 'json'

Puppet::Type.type(:apt_libral).provide(:ralsh) do
  desc 'Support for Puppet managing apt packages from Libral'

  mk_resource_methods
  commands :ralsh => 'ralsh'

  def self.instances
    output = ralsh(['package::apt', '--json', '-l', 'none'])
    resources = JSON.parse(output)['resources']
    resources.collect do |resource|
      # This could be autogenerated from running
      # ralsh -e package::apt
      new({
        :name     => resource['name'],
        :platform => resource['platform'],
        :ensure   => resource['ensure'],
      })
    end
  end

  def self.prefetch(resources)
    instances.each do |prov|
      if resource = resources[prov.name] # rubocop:disable Lint/AssignmentInCondition
        resource.provider = prov
      end
    end
  end

  def exists?
    true
  end
end
