Puppet::Type.type(:apt_libral).provide(:simple) do
  desc 'Support for Puppet managing apt packages from Libral'

  mk_resource_methods
  commands :apt => '/usr/src/ral/data/providers/apt.prov'
  defaultfor :libral_provider => :simple

  def self.instances
    output = apt(['ral_action=list'])
    lines = output.split("\n")
    lines.shift # remove header row
    resources = {}
    lines.each do |line|
      key, value = line.split(":", 2)
      if key == "name"
        $name = value.strip
	resources[$name] = {}
      else
        resources[$name][key] = value.strip
      end
    end
    resources.collect do |name, resource|
      # This could be autogenerated from running
      # apt.prov ral_action=describe
      new({
        :name     => name,
        :platform => resource['platform'],
        :ensure   => resource['ensure'],
      })
    end
  end

  def self.prefetch(resources)
    instances.each do |prov|
      if resource = resources[prov.name] # rubocop:disable Lint/AssignmentInCondition
        resource.provider = prov
      end
    end
  end

  def exists?
    true
  end
end
