#! /bin/bash

# Pack ralsh and supporting files so they can be copied into a Docker
# container. This works on Fedora 25, provided you have the following
# packages installed:
#
# dnf install upx glibc-static libxml2-static zlib-static xz-static libselinux-static
#
# Also, you need to install puppet-agent to build this (we only use that
# for the static libs for augeas, since regrettably Fedora does not ship
# augeas-static yet, see
# https://bugzilla.redhat.com/show_bug.cgi?id=1405600)
#

topdir=$(dirname $0)/..

# Where leatherman is installed
lth_dir=${lth_dir:-/opt/puppetlabs/puppet}

if [ ! -f "${lth_dir}/lib/leatherman_util.a" ]; then
    echo "set lth_dir to the directory that contains static leatherman libraries"
    exit 1
fi

# Build everything
cd ${abs_top_builddir:-$topdir/build}

if [ ! -f CMakeCache.txt ]; then
    echo "set abs_top_builddir to the directory where libral is built"
    exit 1
fi

make

# Reduce the executable as best we can
cd bin
strip -R .note -R .comment -R .eh_frame -R .eh_frame_hdr -s  ralsh
[ -x upx ] && upx ralsh

cd ..
rm -rf dpack
mkdir -p dpack/bin
cp ./bin/ralsh dpack/bin
cp -pr ${topdir}/data dpack
# Snarf up some augeas lenses that we need
lns_src=/usr/share/augeas/lenses/dist
cp -p $lns_src/sep.aug $lns_src/util.aug $lns_src/rx.aug $lns_src/build.aug dpack/data/lenses
rm -rf dpack/data/lenses/tests

find dpack/ -name \*~ -delete

tar czf ralsh-dpack-$(date +%Y-%m-%dT%H.%M).tgz dpack

echo
echo To run ralsh inside a container, run
echo
echo   docker cp $PWD/dpack '<container>:/tmp'
echo   docker exec '<container>' /bin/sh -c '"RALSH_DATA_DIR=/tmp/dpack/data /tmp/dpack/bin/ralsh"'
