#
# Tools image for libral builds. Contains everything besides libral itself
#
FROM fedora:25

ENV PL_BUILD_TOOLS_VER=22.0.3-1
ENV RPMFORGE_RELEASE_VER=0.5.3-1
ENV LEATHERMAN_VER=0.10.1

COPY scripts /usr/src/scripts
RUN /usr/src/scripts/image.sh f25-build

WORKDIR /usr/src

CMD ["/usr/src/scripts/build.sh"]
